// <auto-generated />
namespace Medical_Corporation_Hospital.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class EditTablesToIncludeVirtualKeyWord : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EditTablesToIncludeVirtualKeyWord));
        
        string IMigrationMetadata.Id
        {
            get { return "201903271120174_EditTablesToIncludeVirtualKeyWord"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
